### ISSUE TITLE
Compiling error, Ubuntu 16.04, kinetic

### ISSUE THREAD

**Issue by dkanou** [ADVRHumanoids/ModelInterfaceRBDL#4]
I get this compiling error in a fresh Ubuntu 16.04, kinetic system:

> /advr-superbuild/external/ModelInterfaceRBDL/src/ModelInterfaceRBDL.cpp: In member function ‘virtual bool XBot::ModelInterfaceRBDL::init_model(const string&)’:
> /advr-superbuild/external/ModelInterfaceRBDL/src/ModelInterfaceRBDL.cpp:120:117: error: cannot convert ‘double’ to ‘const VectorNd* {aka const Eigen::Matrix<double, -1, 1>*}’ for argument ‘4’ to ‘void RigidBodyDynamics::Utils::CalcCenterOfMass(RigidBodyDynamics::Model&, const VectorNd&, const VectorNd&, const VectorNd*, double&, RigidBodyDynamics::Math::Vector3d&, RigidBodyDynamics::Math::Vector3d*, RigidBodyDynamics::Math::Vector3d*, RigidBodyDynamics::Math::Vector3d*, RigidBodyDynamics::Math::Vector3d*, bool)’
>      RigidBodyDynamics::Utils::CalcCenterOfMass(_rbdl_model, _q, _qdot, _mass, _tmp_vector3d, nullptr, nullptr, false);

**Comment by liesrock** [comment]
Hi @dkanou , it is actually a superbuild issue solved in: https://github.com/ADVRHumanoids/advr-superbuild/commit/080a461aa4365abbd6f3d611c65ebeae0dcd8c0c

So just pull the latest master of the superbuild and 

```
cd $ROBOTOLOGY_SUPERBUILD/build
cmake ..
make rbdl-update
make rbdl
make ModelInterfaceRBDL
```

Otherwise delete both the sources and the build of rbdl and recompile.

You can check that what I am saying is actually working on Travis: 

https://travis-ci.org/ADVRHumanoids/advr-superbuild/builds/375101152

**Comment by lothas** [comment]
I'm having the same issue and running these commands didn't help

**Comment by pepperig** [comment]
Try to delete both the sources and the build of rbdl and recompile.

**Comment by lothas** [comment]
That didn't work either. Still the same error.
I'm actually getting this error while making https://github.com/EnricoMingo/OpenSoT-superbuild.git from a docker script (also fails inside the docker), so I'd like to resolve the issue in a way that doesn't cause the docker script to fail.

**Comment by pepperig** [comment]
I see. The problem is that you are using a fork of the ADVR superbuild.
Have a look at this commit to understand how to fix it. https://github.com/ADVRHumanoids/advr-superbuild/commit/080a461aa4365abbd6f3d611c65ebeae0dcd8c0c

**Comment by lothas** [comment]
Thanks! I looked into the commit you mentioned and added the tag line to the ProjectsTag.cmake. After removing rbdl I was able to make. Now I need to try adding it to the docker script.
